name: website-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths:
      - 'website'

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
